### ISSUE TITLE
v7.0.0 release tracker

### ISSUE THREAD

**Issue by jbarlow83** [jbarlow83/OCRmyPDF#272]
- [x] pylint
- [x] fix broken remove_colormap in leptonica
- [x] look for APIs to tweak
- [x] deprivatize _objgen and _get_object_by_id in pikepdf
- [ ] prep homebrew ocrmypdf.rb changes
- [x] investigate Travis showing some cache files generated after the fact
- [ ] check in on JPEG2k colorspace
- [ ] final update test cache
- [x] merge or close tests/ignore-masks
- [x] optimize test resources
- [ ] decide on skip text margins or another text on page mode
- [ ] remove pre/post qpdf
